### PR TITLE
Feature/helpful missing content messages

### PR DESCRIPTION
**Pull request by PhotoNomad0**
## Describe what your pull request addresses
- [ ] Fix to show when resource data is loading

## Test Instructions
- can test with: https://deploy-preview-88--create-app.netlify.app/
- [ ] open app to mat 1:1
- [ ] open debug tools
- [ ] in networking disable cache.  set throttling to slow 3g.
- [ ] if you navigate to old testament book, should see loading message in scripture panes for a moment.
- [ ] resources should still load.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/single-scripture-rcl/20)

### CODE REVIEW

**Comment by mannycolon** [comment]
Open mat 1:1 and it loaded Hebrew in the original language pane instead of the UGNT
Screen Shot 2021-03-16 at 3 55 00 PM

**Comment by mannycolon** [comment]
The styling for the status message should match the styling the other cards have (Bold, centered etc)

**Comment by mannycolon** [comment]
Inconsistent styling for the status message 
Screen Shot 2021-03-16 at 3 59 28 PM

**Comment by PhotoNomad0** [comment]
> Inconsistent styling for the status message
> Screen Shot 2021-03-16 at 3 59 28 PM

I would expect the size to be the same as the content (which is based on font size slider).

**Comment by mannycolon** [comment]
Still seeing inconsistent styling for the status message, only happens with Hebrew content. It seems the font size increase we use for Hebrew is messing it up. Should we just remove that when a status message is defined?
Screen Shot 2021-03-18 at 1 30 13 PM

**Review by mannycolon — APPROVED** [review]

**Pull request merged**
