### PR TITLE
Added original quote highlighting to scripture panes 

### PR DESCRIPTION
**Pull request by mannycolon**
- [ ] Open https://deploy-preview-16--single-scripture-rcl.netlify.app/
- [x] Verify that all previous scripture pane features work as expected
- [x]  Verify that the original quote highlighting is working

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/single-scripture-rcl/16)

### CODE REVIEW

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/single-scripture-rcl/16)* status: all files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[src/components/ScriptureCard/ScriptureCard.tsx, line 65 at r1](https://reviewable.io/reviews/unfoldingword/single-scripture-rcl/16#-MUAXU3s-QJdQjztu82q:-MUAXU3u7Gi7AVF-FQBC:b-9g0gv0) ([raw file](https://github.com/unfoldingword/single-scripture-rcl/blob/839fec4924d2e90a85091d35537a8ba4e92682a9/src/components/ScriptureCard/ScriptureCard.tsx#L65)):*
> ```XML
>     // TODO: What are the next two lines useful for? Bruce McLean?
>     const scriptureConfig_ = { ...scriptureConfig }
>     scriptureConfig_.verseObjects = !!scriptureConfig.verseObjects
> ```

Looks like leftover dead code, the scriptureConfig_ is no longer used.

**Comment by PhotoNomad0** [comment]
@mannycolon  Seeing this:

Screen Shot 2021-02-22 at 4 06 48 PM

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/single-scripture-rcl/16)* status: all files reviewed, 2 unresolved discussions (waiting on @mannycolon)

___
*[src/components/ScriptureCard/README.md, line 81 at r1](https://reviewable.io/reviews/unfoldingword/single-scripture-rcl/16#-MUAc9CD1H8Xg5t2aI1Q:-MUAc9CECiFb0jPTd-sT:b-l8a277) ([raw file](https://github.com/unfoldingword/single-scripture-rcl/blob/839fec4924d2e90a85091d35537a8ba4e92682a9/src/components/ScriptureCard/README.md#L81)):*
> ```Markdown
> 
> ///////////////////////////////////////////
> // Enable one of the following bible config lines to see various examples
> ```

This comment should probably be removed.

**Comment by PhotoNomad0** [comment]
Also seeing a strange behavior.  When I click on some words, they turn yellow and additional words in ult and ust turn yellow also.

Here is the initial (correct) highlighting:
Screen Shot 2021-02-22 at 4 46 55 PM

And here is after I clicked a few other words, but not all words are clickable:

Screen Shot 2021-02-22 at 4 45 20 PM

**Comment by PhotoNomad0** [comment]
No longer see the Lemma popups when I hover over the original language word.  It was still working in: https://deploy-preview-60--create-app.netlify.app/:

Screen Shot 2021-02-22 at 4 56 47 PM

**Comment by mannycolon** [comment]
> @mannycolon Seeing this:
> 
> Screen Shot 2021-02-22 at 4 06 48 PM

@PhotoNomad0 
This is happening in the main branch, it seems that it stopped working after your changes to scripture panes settings 
Screen Shot 2021-02-22 at 5 55 13 PM

**Comment by mannycolon** [comment]
> No longer see the Lemma popups when I hover over the original language word. It was still working in: https://deploy-preview-60--create-app.netlify.app/:
> 
> Screen Shot 2021-02-22 at 4 56 47 PM

The Greek scripture pane had the word popover disabled

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/single-scripture-rcl/16)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/single-scripture-rcl/16)* status: all files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[package.json, line 4 at r2](https://reviewable.io/reviews/unfoldingword/single-scripture-rcl/16#-MUB58Ms7XnEJXQGT4QX:-MUB58Ms7XnEJXQGT4QY:bvh58sx) ([raw file](https://github.com/unfoldingword/single-scripture-rcl/blob/417f8d25d66445576e74202e4c793d73ecaf057f/package.json#L4)):*
> ```JSON
>   "name": "single-scripture-rcl",
>   "description": "A React Component Library for Rendering a Single Scripture Resource.",
>   "version": "1.0.0-rc2",
> ```

Don't we want this to be 1.0.0?

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/single-scripture-rcl/16)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
