### PR TITLE
Feature/Create headless RCL

### PR DESCRIPTION
**Pull request by PhotoNomad0**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/single-scripture-rcl/3)

### CODE REVIEW

**Review by mannycolon — CHANGES_REQUESTED** [review]
Pending testing changes on styleguidist

**Comment by mannycolon** [comment]
Testing locally since this repo isn't deployed on Netlify

**Comment by mannycolon** [comment]
When testing locally it says `Module not found: Can't resolve 'scripture-resources-rcl' `
Did you publish `scripture-resources-rcl@3.0.3-alpha`?

**Comment by PhotoNomad0** [comment]
@mannycolon - see that version at https://www.npmjs.com/package/scripture-resources-rcl, but nevertheless I updated to the published version.

**Comment by mannycolon** [comment]
LGTM

**Pull request merged**
